import pandas as pd
from zenml import step


@step
def dynamic_importer() -> str:
    """Dynamically imports data for testing out the model."""
    # Here, we simulate importing or generating some data.
    # In a real-world scenario, this could be an API call, database query, or loading from a file.
    data = {
    "Order": [1, 2],
    "PID": [526301100, 526301101],
    "MS SubClass": [60, 20],
    "Lot Frontage": [65.0, 80.0],
    "Lot Area": [8450, 9600],
    "Overall Qual": [7, 6],
    "Overall Cond": [5, 8],
    "Year Built": [2003, 1976],
    "Year Remod/Add": [2003, 1976],
    "Mas Vnr Area": [196.0, 0.0],
    "BsmtFin SF 1": [706, 978],
    "BsmtFin SF 2": [0, 0],
    "Bsmt Unf SF": [150, 284],
    "Total Bsmt SF": [856, 1262],
    "1st Flr SF": [856, 1262],
    "2nd Flr SF": [854, 0],
    "Low Qual Fin SF": [0, 0],
    "Gr Liv Area": [1710, 1262],
    "Bsmt Full Bath": [1, 0],
    "Bsmt Half Bath": [0, 1],
    "Full Bath": [2, 2],
    "Half Bath": [1, 0],
    "Bedroom AbvGr": [3, 3],
    "Kitchen AbvGr": [1, 1],
    "TotRms AbvGrd": [7, 5],
    "Fireplaces": [1, 0],
    "Garage Yr Blt": [2003, 1976],
    "Garage Cars": [2, 2],
    "Garage Area": [548, 460],
    "Wood Deck SF": [0, 298],
    "Open Porch SF": [61, 0],
    "Enclosed Porch": [0, 0],
    "3Ssn Porch": [0, 0],
    "Screen Porch": [0, 0],
    "Pool Area": [0, 0],
    "Misc Val": [0, 0],
    "Mo Sold": [2, 5],
    "Yr Sold": [2008, 2007],

    # One-hot encoded categorical features
    "MS Zoning_C (all)": [0, 0],
    "MS Zoning_FV": [0, 1],
    "MS Zoning_I (all)": [0, 0],
    "MS Zoning_RH": [0, 0],
    "MS Zoning_RL": [1, 0],
    "MS Zoning_RM": [0, 0],
    "Street_Grvl": [0, 0],
    "Street_Pave": [1, 1],
    "Alley_Grvl": [0, 0],
    "Alley_Pave": [0, 0],
    "Alley_None": [1, 1],
    "Lot Shape_IR1": [1, 0],
    "Lot Shape_IR2": [0, 1],
    "Lot Shape_IR3": [0, 0],
    "Lot Shape_Reg": [0, 0],
    "Land Contour_Bnk": [0, 0],
    "Land Contour_HLS": [0, 0],
    "Land Contour_Low": [0, 0],
    "Land Contour_Lvl": [1, 1],
    "Utilities_AllPub": [1, 1],
    "Utilities_NoSewr": [0, 0],
    "Lot Config_Corner": [0, 1],
    "Lot Config_CulDSac": [1, 0],
    "Lot Config_FR2": [0, 0],
    "Lot Config_FR3": [0, 0],
    "Lot Config_Inside": [0, 0],
    "Land Slope_Gtl": [1, 1],
    "Land Slope_Mod": [0, 0],
    "Land Slope_Sev": [0, 0],


    "Neighborhood_Blmngtn": [0, 0],
    "Neighborhood_Blueste": [0, 0],
    "Neighborhood_BrDale": [0, 0],
    "Neighborhood_BrkSide": [1, 0],
    "Neighborhood_ClearCr": [0, 1],
    "Neighborhood_CollgCr": [0, 0],
    "Neighborhood_Crawfor": [0, 0],
    "Neighborhood_Edwards": [0, 0],
    "Neighborhood_Gilbert": [0, 0],
    "Neighborhood_Greens": [0, 0],
    "Neighborhood_GrnHill": [0, 0],
    "Neighborhood_IDOTRR": [0, 0],
    "Neighborhood_Landmrk": [0, 0],
    "Neighborhood_MeadowV": [0, 0],
    "Neighborhood_Mitchel": [0, 0],
    "Neighborhood_NAmes": [0, 0],
    "Neighborhood_NPkVill": [0, 0],
    "Neighborhood_NWAmes": [0, 0],
    "Neighborhood_NoRidge": [0, 0],
    "Neighborhood_NridgHt": [0, 0],
    "Neighborhood_OldTown": [0, 0],
    "Neighborhood_SWISU": [0, 0],
    "Neighborhood_Sawyer": [0, 0],
    "Neighborhood_SawyerW": [0, 0],
    "Neighborhood_Somerst": [0, 0],
    "Neighborhood_StoneBr": [0, 0],
    "Neighborhood_Timber": [0, 0],
    "Neighborhood_Veenker": [0, 0],

    "Condition 1_Artery": [0, 0],
    "Condition 1_Feedr": [0, 0],
    "Condition 1_Norm": [1, 1],
    "Condition 1_PosA": [0, 0],
    "Condition 1_PosN": [0, 0],
    "Condition 1_RRAe": [0, 0],
    "Condition 1_RRAn": [0, 0],
    "Condition 1_RRNe": [0, 0],
    "Condition 1_RRNn": [0, 0],
    
    "Bldg Type_1Fam": [1, 1],
    "Bldg Type_2fmCon": [0, 0],
    "Bldg Type_Duplex": [0, 0],
    "Bldg Type_Twnhs": [0, 0],
    "Bldg Type_TwnhsE": [0, 0],
    
    "House Style_1.5Fin": [0, 0],
    "House Style_1.5Unf": [0, 0],
    "House Style_1Story": [0, 1],
    "House Style_2.5Unf": [0, 0],
    "House Style_2Story": [1, 0],
    "House Style_SFoyer": [0, 0],
    "House Style_SLvl": [0, 0],
    
    "Roof Style_Flat": [0, 0],
    "Roof Style_Gable": [1, 1],
    "Roof Style_Gambrel": [0, 0],
    "Roof Style_Hip": [0, 0],
    "Roof Style_Mansard": [0, 0],
    "Roof Style_Shed": [0, 0],
    
    "Roof Matl_CompShg": [1, 1],
    "Roof Matl_Tar&Grv": [0, 0],
    "Roof Matl_WdShake": [0, 0],
    "Roof Matl_WdShngl": [0, 0],
    
    "Mas Vnr Type_BrkCmn": [0, 0],
    "Mas Vnr Type_BrkFace": [1, 0],
    "Mas Vnr Type_CBlock": [0, 0],
    "Mas Vnr Type_Stone": [0, 0],
    "Mas Vnr Type_None": [0, 1],
}

    df = pd.DataFrame(data)

    # Convert the DataFrame to a JSON string
    json_data = df.to_json(orient="split")

    return json_data
